// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toyana.Identity.Data;

#nullable disable

namespace Toyana.Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260114221219_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toyana.Identity.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Toyana.Identity.Models.ClientUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ClientUsers");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VendorRoles");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("VendorUsers");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorUserId");

                    b.ToTable("VendorUserPermissions");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserRole", b =>
                {
                    b.Property<Guid>("VendorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("VendorUserId", "VendorRoleId");

                    b.HasIndex("VendorRoleId");

                    b.ToTable("VendorUserRoles");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserPermission", b =>
                {
                    b.HasOne("Toyana.Identity.Models.VendorUser", "VendorUser")
                        .WithMany("Permissions")
                        .HasForeignKey("VendorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorUser");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserRole", b =>
                {
                    b.HasOne("Toyana.Identity.Models.VendorRole", "VendorRole")
                        .WithMany()
                        .HasForeignKey("VendorRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toyana.Identity.Models.VendorUser", "VendorUser")
                        .WithMany("Roles")
                        .HasForeignKey("VendorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorRole");

                    b.Navigation("VendorUser");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUser", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
