// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toyana.Identity.Data;

#nullable disable

namespace Toyana.Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119205829_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toyana.Identity.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.ClientUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_client_users");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_client_users_phone_number");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_client_users_username");

                    b.ToTable("client_users", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("action");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("VendorRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_role_id");

                    b.Property<Guid?>("VendorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_user_id");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("VendorRoleId")
                        .HasDatabaseName("ix_permissions_vendor_role_id");

                    b.HasIndex("VendorUserId")
                        .HasDatabaseName("ix_permissions_vendor_user_id");

                    b.HasIndex("Action", "Scope")
                        .HasDatabaseName("ix_permissions_action_scope");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_roles");

                    b.ToTable("vendor_roles", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_users_username");

                    b.ToTable("vendor_users", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserPermission", b =>
                {
                    b.Property<Guid>("VendorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_user_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("VendorUserId", "PermissionId")
                        .HasName("pk_vendor_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_vendor_user_permissions_permission_id");

                    b.ToTable("vendor_user_permissions", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserRole", b =>
                {
                    b.Property<Guid>("VendorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_user_id");

                    b.Property<Guid>("VendorRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_role_id");

                    b.HasKey("VendorUserId", "VendorRoleId")
                        .HasName("pk_vendor_user_roles");

                    b.HasIndex("VendorRoleId")
                        .HasDatabaseName("ix_vendor_user_roles_vendor_role_id");

                    b.ToTable("vendor_user_roles", (string)null);
                });

            modelBuilder.Entity("Toyana.Identity.Models.Permission", b =>
                {
                    b.HasOne("Toyana.Identity.Models.VendorRole", null)
                        .WithMany("Permissions")
                        .HasForeignKey("VendorRoleId")
                        .HasConstraintName("fk_permissions_vendor_roles_vendor_role_id");

                    b.HasOne("Toyana.Identity.Models.VendorUser", null)
                        .WithMany("Permissions")
                        .HasForeignKey("VendorUserId")
                        .HasConstraintName("fk_permissions_vendor_users_vendor_user_id");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserPermission", b =>
                {
                    b.HasOne("Toyana.Identity.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_permissions_permissions_permission_id");

                    b.HasOne("Toyana.Identity.Models.VendorUser", "VendorUser")
                        .WithMany()
                        .HasForeignKey("VendorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_permissions_vendor_users_vendor_user_id");

                    b.Navigation("VendorUser");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUserRole", b =>
                {
                    b.HasOne("Toyana.Identity.Models.VendorRole", "VendorRole")
                        .WithMany()
                        .HasForeignKey("VendorRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_roles_vendor_roles_vendor_role_id");

                    b.HasOne("Toyana.Identity.Models.VendorUser", "VendorUser")
                        .WithMany("Roles")
                        .HasForeignKey("VendorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_roles_vendor_users_vendor_user_id");

                    b.Navigation("VendorRole");

                    b.Navigation("VendorUser");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Toyana.Identity.Models.VendorUser", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
